name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.1
  
    - name: Build
      run: |
        yarn
        yarn build
        go mod tidy
        CGO_ENABLED=0 go build
      
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: messer
        path: messer
